### ISSUE TITLE
nothing to commit, working tree clean

### ISSUE THREAD

**Issue by hrodrigo7** [Albert-Alvarez/masb#4]
Hello Albert,
I'm trying to do the stm of the first practice but when I change the code and try to do a 'git commit' it tells me that there is nothing to commit (I attach a photo). I have not executed the git commit command before for this new version.
![err](https://user-images.githubusercontent.com/75335126/108251472-bb18f300-7157-11eb-954d-119d3fee4127.PNG)
![1](https://user-images.githubusercontent.com/75335126/108335322-19cf8280-71d3-11eb-9e4c-c74560484b7c.PNG)
![2](https://user-images.githubusercontent.com/75335126/108335356-2653db00-71d3-11eb-9b39-43ac14babe1c.PNG)
![folder](https://user-images.githubusercontent.com/75335126/108335474-4be0e480-71d3-11eb-87ab-2f77f16c2cc1.PNG)

**Comment by Albert-Alvarez** [comment]
If git tells you that there is nothing to commit that's because there isn't any file in the stage. The files are added to the stage using the git add command, which you have already done. So, that means that from the last commit you have not edited any file in the repository, no files have been added to the stage area with the git add command, and, therefore, there is nothing to commit.

Check that there are any files in your repository folder (maybe you have created the project in another folder accidentally), or that you have already edited any file.

Attach to this issue an image of the terminal for the output of the git log and git status, respectively.

**Comment by hrodrigo7** [comment]
The fact is that I did have edited the files in the repository and there should be something to commit. I have also thought that it could be that the project is in another folder but I think it is in the correct place (I also attach the folder of the project).

The images of the errors and the folder are attached in the main issue.

**Comment by Albert-Alvarez** [comment]
It is difficult to give you a solution without being able to have the computer in front. If you agree, I'll send you an email to meet virtually this afternoon, we'll see it and then I'll give the answer here so that the rest of my colleagues also have the answer.

Meanwhile, install [TeamViewer](https://www.teamviewer.com/es/) and Microsoft Teams (available as student on [https://nuvol.ub.edu/](https://nuvol.ub.edu/)) on your computer.

**Comment by Albert-Alvarez** [comment]
In the remote assistance, the above-mentioned facts were not observed and everything seems to be working correctly. I close this issue and, if you have any further questions, do not hesitate to open a new one.
